steps:
  - name: ":rubocop:"
    command: "bash scripts/ci/rubocop.sh"
    artifact_paths:
     - "log/**/*"
    env:
      RAILS_ENV: test
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: docker-compose.yml
    agents:
      queue: $BUILDKITE_AGENT_META_DATA_QUEUE

  - name: ":eslint:"
    command: "bash scripts/ci/eslint.sh"
    artifact_paths:
    - "log/**/*"
    env:
      RAILS_ENV: test
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: docker-compose.yml
    agents:
      queue: $BUILDKITE_AGENT_META_DATA_QUEUE

  - name: ":rspec:"
    command: "bash scripts/ci/rspec.sh"
    artifact_paths:
     - "log/**/*"
     - "tmp/capybara/**/*"
    env:
      RAILS_ENV: test
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: docker-compose.yml
    parallelism: 20
    agents:
      queue: $BUILDKITE_AGENT_META_DATA_QUEUE
